[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "attrs>=25.3.0",
    "black>=25.1.0",
    "isort>=6.0.1",
    "pydantic>=2.11.7",
]
